# Generated by Django 4.2.7 on 2023-11-23 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsTable',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('status', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=200)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('amount_status', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('savings', 'Savings')], max_length=200)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('loan', 'Loan'), ('other', 'Others')], max_length=200)),
                ('categorys', models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('shopping', 'Shopping'), ('snacks', 'Snacks'), ('medical', 'Medical'), ('telephone', 'Telephone'), ('entertainment', 'Entertainment'), ('bill', 'Bills'), ('education', 'Education'), ('social', 'Social'), ('loan', 'Loan'), ('other', 'Other')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
